import json
from pathlib import Path
P=Path(__file__).resolve().parents[1]/'public/data'
sites=json.loads((P/'sites.geojson').read_text())['features']
manual='https://wdfw.wa.gov/publications/02061'
snippets=[
 dict(id='WDFW 2019 • assessment',title='What is a passage barrier?',text='Total and partial passage classifications describe assessed obstruction at a structure; passability is not proof of access through the whole stream network.',url=manual,keywords=['total','partial','passable','definition','barrier']),
 dict(id='WDFW 2019 • habitat survey',title='Habitat is not connectivity',text='Upstream habitat gain requires habitat survey and fish-access information; a single crossing record cannot establish that coho or kokanee can reach all habitat above it.',url=manual,keywords=['habitat','above','access','gain','coho','kokanee']),
 dict(id='Ecology • 6PPD',title='First rain, road runoff',text='6PPD-quinone from tire wear is toxic to coho at very low concentrations; the first-flush banner is a rain-and-dry-days demo heuristic, not a chemical measurement.',url='https://ecology.wa.gov/waste-toxics/reducing-toxic-chemicals/reducing-toxic-chemicals-washington/6ppd',keywords=['first','rain','6ppd','flush','tire','storm']),
 dict(id='WRIA 8 • 2025 progress',title='Room for more shade',text='The WRIA 8 2025 progress report records 28.6 acres of Sammamish River riparian planting against a 69-acre goal, about 41 percent.',url='https://govlink.org/watersheds/8/reports/WRIA82025ProgressReport.pdf',keywords=['shade','riparian','plant','goal']),
 dict(id='Sammamish • Zackuse restoration',title='A return route for kokanee',text='The City of Sammamish describes Zackuse Creek fish-passage and stream restoration as work to improve native kokanee spawning habitat.',url='https://www.sammamish.us/projects/zacuse-creek-fish-passage-restoration/',keywords=['zackuse','restoration']),
 dict(id='King County • 2018 kokanee',title='A historical warning',text='Fewer than 20 kokanee returned in the 2017–18 winter run; this is historical context, not a current population estimate.',url='https://kcemployees.com/2018/05/11/taking-emergency-action-to-prevent-the-possible-extinction-of-native-kokanee-salmon/',keywords=['crisis','winter','2018','population']),
 dict(id='King County • 6PPD sampling',title='Sampling, not a sensor',text='King County documents 6PPD-quinone sampling context at the Sammamish River near SR 522 and I-405; this app provides no live chemistry readings.',url='https://your.kingcounty.gov/dnrp/library/2024/kcr3832/kcr3832.pdf',keywords=['sampling','405','chemistry'])]
for f in json.loads((P/'impaired.geojson').read_text())['features']:
 p=f['properties']
 if 'sammamish' in str(p.get('ListingWaterbodyName','')).lower() and any(t in str(p.get('ParameterName','')).lower() for t in ['temperature','oxygen']):
  snippets.append(dict(id='303(d) '+str(p['ListingNumber']),title=p['ListingWaterbodyName']+' • '+p['ParameterName'],text=f"Ecology listing {p['ListingNumber']} identifies {p['ListingWaterbodyName']} for {p['ParameterName']} in category {p['CategoryCode']}; this assessment is not a live water-quality reading or a verified join to a selected crossing.",url='https://apps.ecology.wa.gov/ApprovedWQA/ApprovedPages/ApprovedSearch.aspx',keywords=['303','impaired',p['ListingWaterbodyName'].lower(),p['ParameterName'].lower()]+(['heat'] if 'temperature' in p['ParameterName'].lower() else ['oxygen'])))
(P/'snippets.json').write_text(json.dumps(snippets,indent=2))
def match(fn):return next((s for s in sites if fn(s['properties'])),None)
def record(title,desc,fn,tag='Inventory story'):
 s=match(fn)
 return dict(title=title,description=desc,tag=tag,siteId=s['properties']['id'] if s else None,coordinates=s['geometry']['coordinates'] if s else None,illustrative=False)
stories=[record('Zackuse Creek','Follow the kokanee restoration story along the Louis Thompson corridor. The selected official pin is on Zackuse Creek; corridor/project boundaries are not joined.',lambda p:p['stream']=='Zackuse Cr' and p['status']=='passable'),dict(title='Issaquah Creek · State Park',description='Restoration and kokanee/Chinook context at the lake mouth. Illustrative pin pending live join; no barrier classification is asserted.',tag='Place story',siteId=None,coordinates=[-122.059,47.558],illustrative=True),dict(title='Sammamish River · second squeeze',description='Temperature and dissolved oxygen listings add another pressure. Riparian planting: 28.6 of 69 acres (41%) toward the 2025 goal.',tag='Water quality',siteId=None,coordinates=[-122.122,47.718],illustrative=True),dict(title='Sammamish River · I-405',description='King County 6PPD-q sampling context near SR 522 and I-405. Illustrative pin pending live join, not a monitoring station reading.',tag='Runoff',siteId=None,coordinates=[-122.184,47.756],illustrative=True),record('Juanita Creek','Explore the official inventory around Juanita Creek.',lambda p:'juanita' in p['stream'].lower()),record('Not only highways','A driveway culvert is part of the same stream network. Driveway is recorded in the road name; the feature type remains culvert.',lambda p:'driveway' in p['road'].lower() and p['feature']=='Culvert'),record('A way through','A passable crossing is a useful contrast; it does not guarantee that upstream or downstream crossings are passable.',lambda p:p['status']=='passable' and p['stream']=='Zackuse Cr'),record('A partial barrier','Some passage is recorded here, but passage is not the same as unobstructed access.',lambda p:p['status']=='partial'),record('Fish use · total barrier','Fish use is yes while passage is recorded as total blockage.',lambda p:p['fishUse']=='Yes' and p['status']=='total'),dict(title='Heat without a crossing',description='A river reach can be impaired without a mapped barrier at this location. No crossing is selected and no barrier status is inferred.',tag='Water quality',siteId=None,coordinates=[-122.129,47.704],illustrative=True),dict(title='Redmond · watch from the trail',description='Spawn-watch context: observe quietly from public trail space, keep out of the water, and leave fish undisturbed. No live sighting or guaranteed viewing is claimed.',tag='Spawn watch',siteId=None,coordinates=[-122.126,47.677],illustrative=True),record('Highway / city responsibility','This highway crossing has a WSDOT project label. Compare its owner type with a City-owned crossing in the inventory; ownership type is not a named contact.',lambda p:p.get('ProjectName')=='WSDOT' and p['status']=='total')]
city=match(lambda p:p['owner']=='City');stories[-1]['compareSiteId']=city['properties']['id']
(P/'stories.json').write_text(json.dumps(stories,indent=2));print('snippets',len(snippets),'stories',len(stories))
